# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1EeaW6ugh6aEH6I1j1jA7bfD32kEF8y7J
"""

x=5
print(x)
print(f"变数x的值得是:{x}")
print(f"变数x的记忆体地址是:{id(x)}")