# -*- coding: utf-8 -*-
"""Untitled2.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1tU8M3wjF4MbDAQoCfgCNLim3eOn32bVQ
"""

import os
os.mkdir('CS')
file_path = os.path.join('CS','homework.txt')
with open(file_path,'w')as file:
    file.write('4112028022_馮靖茹')
with open(file_path,'r')as file:
    content = file.read()
print("檔案內容:",content)
print("\n檔案資訊:")
print("資訊:",os.path.getsize(file_path),"bytes")
os.remove(file_path)
os.rmdir('CS')