# -*- coding: utf-8 -*-
"""Untitled3.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1XcLdyc3OaFMHXH3JQA9qrXXHibDNQQ8e
"""

import sqlite3
conn = sqlite3.connect('BBQ.db')
cursor = conn.cursor()
cursor.execute('''
               CREATE TABLE IF NOT EXISTS meats (
                   id INTEGER PRIMARY KEY,
                   name TEXT,
                   price INTEGER,
                   quantity INTEGER
                   )''')
cursor.execute("INSERT INTO meats (name, price, quantity) VALUES ('Chicken', 30 , 5)")
cursor.execute("INSERT INTO meats (name, price, quantity) VALUES ('Beaf', 55, 10)")
cursor.execute("INSERT INTO meats (name, price, quantity) VALUES ('Pork', 40, 15)")

cursor.execute("UPDATE meats SET price = 35 WHERE name = 'Pork'")
conn.commit()
cursor.execute("UPDATE meats SET quantity = 30 WHERE name ='Chicken'")
conn.commit()
cursor.execute("DELETE FROM meats WHERE price = 40")
conn.commit()

cursor.execute("SELECT * FROM meats")
meats = cursor.fetchall()

print("表格內容:")
for meat in meats:
    print(meat)